esphome:
  name: ct
  friendly_name: CT

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  # level: verbose
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  # Wemos D1 Mini
  # tx_pin: 1
  # rx_pin: 3
  # Wemos C3 Mini
  tx_pin: 21
  rx_pin: 20
  baud_rate: 9600
  parity: NONE

modbus:
  flow_control_pin: 6
  id: modbus1

modbus_controller:
  - id: hdhk
    address: 1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 30s
sensor:
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Version number"
    id: "version"
    register_type: holding
    address: 0x0000
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel A Current"
    id: "current_a"
    register_type: holding
    address: 0x0008
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel B Current"
    id: "current_b"
    register_type: holding
    address: 0x0009
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel C Current"
    id: "current_c"
    register_type: holding
    address: 0x000A
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel D Current"
    id: "current_D"
    register_type: holding
    address: 0x000B
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel E Current"
    id: "current_e"
    register_type: holding
    address: 0x000C
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel F Current"
    id: "current_f"
    register_type: holding
    address: 0x000D
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel G Current"
    id: "current_g"
    register_type: holding
    address: 0x000E
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel H Current"
    id: "current_h"
    register_type: holding
    address: 0x000F
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel I Current"
    id: "current_i"
    register_type: holding
    address: 0x00010
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel J Current"
    id: "current_j"
    register_type: holding
    address: 0x0011
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel K Current"
    id: "current_k"
    register_type: holding
    address: 0x0012
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel L Current"
    id: "current_l"
    register_type: holding
    address: 0x0013
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel M Current"
    id: "current_m"
    register_type: holding
    address: 0x0014
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel N Current"
    id: "current_n"
    register_type: holding
    address: 0x0015
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel O Current"
    id: "current_o"
    register_type: holding
    address: 0x0016
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: hdhk
    name: "Channel P Current"
    id: "current_p"
    register_type: holding
    address: 0x0017
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current

