esphome:
  name: "sdm"
  friendly_name: "SDM120M ModBus Energy meter"

esp8266:
  board: esp01_1m

logger:
    baud_rate: 0

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:

captive_portal:

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  parity: NONE

modbus:
  flow_control_pin: 2
  id: modbus1

modbus_controller:
  - id: sdm
    address: 1
    modbus_id: modbus1
    setup_priority: -10

sensor:
  - platform: modbus_controller
    modbus_controller_id: sdm
    name: "Voltage"
    id: "voltage"
    register_type: read
    address: 0x0000
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: "V"
    state_class: measurement
    device_class: voltage
  - platform: modbus_controller
    modbus_controller_id: sdm
    name: "Current"
    id: "current"
    register_type: read
    address: 0x0006
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: "A"
    state_class: measurement
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: sdm
    name: "Power"
    id: "power"
    register_type: read
    address: 0x000C
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: "W"
    state_class: measurement
    device_class: power
  - platform: modbus_controller
    modbus_controller_id: sdm
    name: "Energy"
    id: "energy"
    register_type: read
    address: 0x0156
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: "kWh"
    state_class: total
    device_class: energy
